[versions]
agp = "8.13.0"
coil = "3.3.0"
coilGif = "2.6.0"
coilGifVersion = "2.7.0"
coilVersion = "1.4.0"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxCoroutinesCore = "1.10.2"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
osmdroidAndroid = "6.1.20"
osmdroidMapsforge = "6.1.20"
preference = "1.2.1"
timber = "5.0.1"
animationCoreLint = "1.9.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference" }
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilVersion" }
coil-compose-android = { module = "io.coil-kt.coil3:coil-compose-android", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coilVersion" }
coil-gif-v260 = { module = "io.coil-kt:coil-gif", version.ref = "coilGif" }
coil-gif-v270 = { module = "io.coil-kt:coil-gif", version.ref = "coilGifVersion" }
coil-kt-coil = { module = "io.coil-kt:coil", version.ref = "coilVersion" }
coil-kt-coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-kt-coil-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil" }
coil3-coil-compose = { module = "io.coil-kt.coil3:coil-compose" }
coil3-coil-gif = { module = "io.coil-kt.coil3:coil-gif" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
osmdroid-android = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroidAndroid" }
osmdroid-mapsforge = { module = "org.osmdroid:osmdroid-mapsforge", version.ref = "osmdroidMapsforge" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
androidx-compose-animation-core-lint = { group = "androidx.compose.animation", name = "animation-core-lint", version.ref = "animationCoreLint" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

